"""How long a selector is likely to keep working, judged from its shape.

A selector cannot be tested for durability — that would need tomorrow's page.
What it can be judged on is what it *depends on*, and the dependencies differ
enormously in how long they survive a redesign:

.. code-block:: text

    #main-content            an id somebody chose on purpose
    [data-spec-id]           a data attribute the page's own code relies on
    .css-1x2y3z4             a build artefact, regenerated by the next deploy
    div > div:nth-child(3)   a description of today's layout, nothing more

The last two break on changes nobody would think of as breaking changes, and
they break silently: a scraper does not crash when a selector stops matching, it
returns nothing, forever, at scale. So fragility is scored, reported next to
every field, and a *critical* field resting only on a fragile selector is a
reason to refuse certification rather than a note in a log.

The scoring is deliberately mechanical and explains itself. Every penalty names
the thing it saw, so an operator disagreeing with a verdict can see exactly
which part of the selector caused it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class Reliability(StrEnum):
    """How much of a redesign a selector is expected to survive."""

    STABLE = "STABLE"
    MEDIUM = "MEDIUM"
    FRAGILE = "FRAGILE"

    @property
    def is_acceptable_for_critical(self) -> bool:
        """May a critical field rest on this alone?

        MEDIUM is allowed: plenty of perfectly good pages offer nothing better
        than a well-named class. FRAGILE is not, because a critical field that
        disappears takes the record with it.
        """

        return self is not Reliability.FRAGILE


#: Positional selectors describe today's layout and nothing else. Inserting one
#: banner above the list moves every index by one, and nothing anywhere fails
#: loudly.
_POSITIONAL = re.compile(r":nth-(child|of-type|last-child|last-of-type)\b")

#: Hashed class names from CSS modules / styled-components / Tailwind JIT.
#: Regenerated by the next build, and matching them means depending on a build
#: artefact rather than on the page.
_GENERATED_CLASS = re.compile(
    r"\.(?:[a-zA-Z]{1,8}[-_])?[a-zA-Z0-9]*(?:[0-9][a-z]|[a-z][0-9])[a-zA-Z0-9]*\b"
)
_HASH_LIKE = re.compile(r"\.[a-zA-Z]*[-_][a-f0-9]{5,}\b|\.[a-zA-Z]{0,3}[a-f0-9]{6,}\b")

#: Attributes a page's own behaviour depends on. If the site breaks them, the
#: site breaks too, which is the best guarantee a scraper can have.
_SEMANTIC_ATTRIBUTE = re.compile(r"\[(data-[a-z0-9-]+|itemprop|property|name|role)[\]=]")

_ID_SELECTOR = re.compile(r"#[a-zA-Z][\w-]*")
_TEST_ATTRIBUTE = re.compile(r"\[data-(testid|test-id|qa|cy)[\]=]")

#: Structural HTML. Not a guarantee, but a page that stops using <article> for
#: articles has changed in a way worth noticing anyway.
#: Preceded by a boundary that is NOT `#`, `.` or `-`, so `#main-content`
#: counts as an id and not as the <main> element.
_SEMANTIC_TAG = re.compile(
    r"(?<![#.\w-])\b(article|main|nav|header|footer|section|table|time)\b(?![-\w])"
)

#: How deep a descendant chain may go before it is describing the DOM's shape
#: rather than the content's identity.
MAX_REASONABLE_DEPTH = 4


@dataclass(frozen=True)
class SelectorJudgement:
    """One selector, judged, with the reasons kept."""

    selector: str
    reliability: Reliability
    score: int
    signals: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        return {
            "selector": self.selector,
            "reliability": self.reliability.value,
            "score": self.score,
            "signals": list(self.signals),
        }

    def describe(self) -> str:
        return f"{self.reliability.value:<8} {self.selector}  ({'; '.join(self.signals) or 'no signals'})"


def judge_selector(selector: str) -> SelectorJudgement:
    """Score one CSS selector. Higher is sturdier.

    The score is an accounting device, not a measurement of the world: it exists
    so the reasons compose, and so a selector with one bad property and three
    good ones does not get the same verdict as one with nothing going for it.
    """

    text = (selector or "").strip()
    if not text:
        return SelectorJudgement("", Reliability.FRAGILE, -100, ("empty selector",))

    score = 0
    signals: list[str] = []

    if _ID_SELECTOR.search(text):
        score += 3
        signals.append("uses an id")
    if _SEMANTIC_ATTRIBUTE.search(text):
        score += 3
        signals.append("uses a semantic data/schema attribute")
    if _TEST_ATTRIBUTE.search(text):
        # Worth something and not worth much: a test hook is a promise to the
        # site's own test suite, not to us, and it gets deleted when the test
        # does.
        score += 1
        signals.append("uses a test hook, which is not a public contract")
    if _SEMANTIC_TAG.search(text):
        score += 1
        signals.append("anchored on a semantic element")

    if _POSITIONAL.search(text):
        score -= 4
        signals.append("positional: one inserted element moves it silently")
    generated = bool(_HASH_LIKE.search(text) or _GENERATED_CLASS.search(text))
    if generated:
        score -= 4
        signals.append("class name looks generated; the next build changes it")

    depth = _depth(text)
    if depth > MAX_REASONABLE_DEPTH:
        score -= 2
        signals.append(f"{depth} levels deep: describes the layout, not the content")
    if ">" in text and depth > 2:
        score -= 1
        signals.append("direct-child chain: any wrapper element breaks it")
    if not generated and text.count(" ") == 0 and text.startswith(".") and depth == 1:
        score += 1
        signals.append("single stable-looking class")

    return SelectorJudgement(text, _classify(score), score, tuple(signals))


def judge_json_path(path: str) -> SelectorJudgement:
    """Score a JSON path.

    JSON paths are structurally sturdier than CSS: a key is chosen by whoever
    designed the payload and renaming it breaks that API's own consumers. What
    is fragile in JSON is *position* — ``rows.0.name`` says the first row is the
    one we want, and nothing guarantees the order.
    """

    text = (path or "").strip()
    if not text:
        return SelectorJudgement("", Reliability.FRAGILE, -100, ("empty path",))

    score = 2
    signals = ["named JSON keys are chosen deliberately"]
    parts = text.split(".")
    if any(part.isdigit() for part in parts):
        score -= 3
        signals.append("indexes a position: nothing guarantees the ordering")
    if len(parts) > 6:
        score -= 1
        signals.append(f"{len(parts)} levels deep")
    if "[*]" in text:
        score += 1
        signals.append("wildcard over a collection rather than one index")
    return SelectorJudgement(text, _classify(score), score, tuple(signals))


def _classify(score: int) -> Reliability:
    if score >= 3:
        return Reliability.STABLE
    if score >= 0:
        return Reliability.MEDIUM
    return Reliability.FRAGILE


def _depth(selector: str) -> int:
    normalised = selector.replace(">", " ").replace("+", " ").replace("~", " ")
    return len([part for part in normalised.split() if part])


@dataclass(frozen=True)
class ExtractorJudgement:
    """One field's extraction path, judged end to end."""

    field: str
    kind: str
    locator: str
    judgement: SelectorJudgement
    importance: str = "optional"

    @property
    def blocks_certification(self) -> bool:
        """A critical field that rests only on something fragile."""

        return (
            self.importance == "critical"
            and not self.judgement.reliability.is_acceptable_for_critical
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "field": self.field,
            "kind": self.kind,
            "importance": self.importance,
            **self.judgement.to_dict(),
            "blocks_certification": self.blocks_certification,
        }


#: Extractor kinds that read a structure the site publishes on purpose. They are
#: not scored as selectors because there is no selector to score: the locator is
#: the standard itself.
STRUCTURED_KINDS = frozenset({"json_ld", "app_state", "meta", "json"})

#: The last resort. A heuristic finds something on most pages and can be wrong
#: on all of them without anything looking unusual, so a critical field resting
#: only on one is refused certification.
HEURISTIC_KINDS = frozenset({"heuristic"})


def judge_extractor(
    *, field_name: str, kind: str, locator: str = "", importance: str = "optional"
) -> ExtractorJudgement:
    """Judge one field's path through one extractor."""

    if kind in HEURISTIC_KINDS:
        judgement = SelectorJudgement(
            locator or kind,
            Reliability.FRAGILE,
            -2,
            ("heuristic: finds something on any page, including the wrong thing",),
        )
    elif kind in STRUCTURED_KINDS and not locator:
        judgement = SelectorJudgement(
            kind, Reliability.STABLE, 4, (f"{kind} is a structure the site publishes",)
        )
    elif kind in {"json", "app_state"} or (
        locator.count(".") and not any(c in locator for c in "#[>: ")
    ):
        judgement = judge_json_path(locator)
    else:
        judgement = judge_selector(locator)
    return ExtractorJudgement(
        field=field_name,
        kind=kind,
        locator=locator or kind,
        judgement=judgement,
        importance=importance,
    )


def summarise(judgements: list[ExtractorJudgement]) -> dict[str, Any]:
    """Counts an operator can act on, plus what would block certification."""

    counts = {level.value: 0 for level in Reliability}
    for item in judgements:
        counts[item.judgement.reliability.value] += 1
    blocking = [j for j in judgements if j.blocks_certification]
    return {
        "by_reliability": counts,
        "fragile_critical_fields": sorted({j.field for j in blocking}),
        "blocks_certification": bool(blocking),
        "judgements": [j.to_dict() for j in judgements],
    }
